### ISSUE TITLE
Variant Tracker Project Reference documentation tasks

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-google-sheets#45]
Additional documentation tasks for the "Variant Tracker Project Reference.md" in the project:

- [x] Add bullet points to the "Deploying Changes to Functions and Updating Existing Reports" section to clearly delineate steps
- [x] Add a link to the Google Drive drive directory where the spreadsheet reports live
- [x] Add a high level documentation regarding the relationship between the appScript code local to each spreadsheet and the shared library appScript code in the VariationTrackerProject. Add a direct link to the VariationTrackerProject code.
- [x] Add a section regarding how when making modifications to the sheets, we only want certain sheets to show (home, alerts, priorities, tracking) when modifications are done. All others that are big query related or extract related should be hidden when changes are complete.
- [x] Add a section describing the relationship between the hidden big query sheets ("priorities by release" and "alerts by release") and their related extract hidden sheets ("priority extract" and "alert extract") and further, their relationship to the display sheets ("priorities" and "alerts").

**Comment by RyanFWebb** [comment]
Completed and ready for review.

**Comment by larrybabb** [comment]
great job. good baseline.
